### ISSUE TITLE
2017-05 enhancements

### ISSUE THREAD

**Issue by isedwards** [starplayerpc/starplayerpc#16]
- [ ] Play and loop beginning/end (https://github.com/starplayerpc/starplayerpc/issues/4)
- [ ] Play but skip beginning/end (https://github.com/starplayerpc/starplayerpc/issues/5)
- [ ] Playlist double-click (https://github.com/starplayerpc/starplayerpc/issues/7)
- [ ] Investigate unexpected emptying of playlist (https://github.com/starplayerpc/starplayerpc/issues/11)
- [ ] Highlight when media files do not exist (https://github.com/starplayerpc/starplayerpc/issues/14)
